// Code generated by OpenTelemetry Weaver from telemetry/registry; DO NOT EDIT.

package telemetry

import (
	"context"
	"sync/atomic"
	"time"

	"github.com/ArthurSens/maintainer-cockpit/internal/storage"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

const (
	InstrumentationName      = "github.com/ArthurSens/maintainer-cockpit"
	InstrumentationVersion   = "0.0.0"
	GenAISemanticConventions = "v1.44.0"
)

var (
	instrumentsReady        atomic.Bool
	analysisAttempts        metric.Int64Counter
	analysisSuccesses       metric.Int64Counter
	providerFailures        metric.Int64Counter
	schemaFailures          metric.Int64Counter
	unknownAnalyses         metric.Int64Counter
	collectionFailures      metric.Int64Counter
	collectionCacheHits     metric.Int64Counter
	collectionCacheMisses   metric.Int64Counter
	collectionCacheBypasses metric.Int64Counter
	forcedReconciliations   metric.Int64Counter
	rateLimitWaits          metric.Int64Counter
	rateLimitFailures       metric.Int64Counter
	genAIOperationDuration  metric.Float64Histogram
	genAITokenUsage         metric.Int64Histogram
)

func registerGeneratedInstruments(store *storage.Store) error {
	meter := otel.Meter(InstrumentationName, metric.WithInstrumentationVersion(InstrumentationVersion))
	var err error
	if analysisAttempts, err = meter.Int64Counter(AnalysisAttemptsMetricName); err != nil {
		return err
	}
	if analysisSuccesses, err = meter.Int64Counter(AnalysisSuccessesMetricName); err != nil {
		return err
	}
	if providerFailures, err = meter.Int64Counter(ProviderFailuresMetricName); err != nil {
		return err
	}
	if schemaFailures, err = meter.Int64Counter(SchemaValidationFailuresMetricName); err != nil {
		return err
	}
	if unknownAnalyses, err = meter.Int64Counter(UnknownAnalysesMetricName); err != nil {
		return err
	}
	if collectionFailures, err = meter.Int64Counter(CollectionFailuresMetricName); err != nil {
		return err
	}
	if collectionCacheHits, err = meter.Int64Counter(CollectionCacheHitsMetricName); err != nil {
		return err
	}
	if collectionCacheMisses, err = meter.Int64Counter(CollectionCacheMissesMetricName); err != nil {
		return err
	}
	if collectionCacheBypasses, err = meter.Int64Counter(CollectionCacheBypassesMetricName); err != nil {
		return err
	}
	if forcedReconciliations, err = meter.Int64Counter(
		CollectionForcedReconciliationsMetricName,
	); err != nil {
		return err
	}
	if rateLimitWaits, err = meter.Int64Counter(GitHubRateLimitWaitsMetricName); err != nil {
		return err
	}
	if rateLimitFailures, err = meter.Int64Counter(
		GitHubRateLimitTerminalFailuresMetricName,
	); err != nil {
		return err
	}
	if genAIOperationDuration, err = meter.Float64Histogram(
		GenAIClientOperationDurationMetricName, metric.WithUnit("s"),
	); err != nil {
		return err
	}
	if genAITokenUsage, err = meter.Int64Histogram(
		GenAIClientTokenUsageMetricName, metric.WithUnit("{token}"),
	); err != nil {
		return err
	}
	if err := registerGenAIAttributionInstruments(meter); err != nil {
		return err
	}
	queueDepth, err := meter.Int64ObservableGauge(QueueDepthMetricName)
	if err != nil {
		return err
	}
	staleAnalyses, err := meter.Int64ObservableGauge(StaleAnalysesMetricName)
	if err != nil {
		return err
	}
	queueAge, err := meter.Float64ObservableGauge(
		QueueOldestAgeMetricName,
		metric.WithUnit("s"),
	)
	if err != nil {
		return err
	}
	collectionSuccess, err := meter.Int64ObservableGauge(
		CollectionLastSuccessMetricName,
		metric.WithUnit("s"),
	)
	if err != nil {
		return err
	}
	_, err = meter.RegisterCallback(func(ctx context.Context, observer metric.Observer) error {
		refresh, err := store.RefreshStatus(ctx)
		if err != nil {
			return err
		}
		analysis, err := store.AnalysisStatus(ctx)
		if err != nil {
			return err
		}
		observer.ObserveInt64(queueDepth, int64(refresh.Queued),
			metric.WithAttributes(attribute.String("maintainer_cockpit.queue.type", "collection")))
		observer.ObserveInt64(queueDepth, int64(analysis.Queued),
			metric.WithAttributes(attribute.String("maintainer_cockpit.queue.type", "analysis")))
		observer.ObserveInt64(staleAnalyses, int64(analysis.Stale))
		now := time.Now().UTC()
		if refresh.Oldest != nil {
			observer.ObserveFloat64(queueAge, now.Sub(*refresh.Oldest).Seconds(),
				metric.WithAttributes(attribute.String("maintainer_cockpit.queue.type", "collection")))
		}
		if analysis.Oldest != nil {
			observer.ObserveFloat64(queueAge, now.Sub(*analysis.Oldest).Seconds(),
				metric.WithAttributes(attribute.String("maintainer_cockpit.queue.type", "analysis")))
		}
		repositories, err := store.ListRepositoryRefreshes(ctx)
		if err != nil {
			return err
		}
		for _, repository := range repositories {
			if repository.LastSuccessful != nil {
				observer.ObserveInt64(collectionSuccess, repository.LastSuccessful.Unix(),
					metric.WithAttributes(attribute.String("maintainer_cockpit.repository", repository.Repository)))
			}
		}
		return nil
	}, queueDepth, staleAnalyses, queueAge, collectionSuccess)
	if err == nil {
		instrumentsReady.Store(true)
	}
	return err
}

// StartCollection records one repository collection attempt.
func StartCollection(ctx context.Context, repository string) (context.Context, func(bool)) {
	if !instrumentsReady.Load() {
		return ctx, func(bool) {}
	}
	ctx, span := otel.Tracer(InstrumentationName).Start(
		ctx, "maintainer_cockpit.collection",
		trace.WithAttributes(attribute.String("maintainer_cockpit.repository", repository)),
	)
	return ctx, func(success bool) {
		if !success {
			collectionFailures.Add(ctx, 1,
				metric.WithAttributes(attribute.String("maintainer_cockpit.repository", repository)))
			span.SetStatus(codes.Error, "collection failed")
		}
		span.End()
	}
}

// RecordCollectionCache records successful cache lookup outcomes.
func RecordCollectionCache(repository string, hits, misses, bypasses int) {
	if !instrumentsReady.Load() {
		return
	}
	ctx := context.Background()
	attributes := metric.WithAttributes(
		attribute.String("maintainer_cockpit.repository", repository),
	)
	if hits > 0 {
		collectionCacheHits.Add(ctx, int64(hits), attributes)
	}
	if misses > 0 {
		collectionCacheMisses.Add(ctx, int64(misses), attributes)
	}
	if bypasses > 0 {
		collectionCacheBypasses.Add(ctx, int64(bypasses), attributes)
	}
}

// RecordForcedReconciliation records an administrator-forced reconciliation.
func RecordForcedReconciliation(repository string, forced bool) {
	if !instrumentsReady.Load() || !forced {
		return
	}
	attributes := metric.WithAttributes(
		attribute.String("maintainer_cockpit.repository", repository),
	)
	forcedReconciliations.Add(context.Background(), 1, attributes)
}

// RecordGitHubRetry records bounded rate-limit waits and terminal failures.
func RecordGitHubRetry(state, reason string) {
	if !instrumentsReady.Load() {
		return
	}
	attributes := metric.WithAttributes(
		attribute.String("maintainer_cockpit.github.rate_limit.type", reason),
	)
	switch state {
	case "waiting":
		rateLimitWaits.Add(context.Background(), 1, attributes)
	case "failed":
		rateLimitFailures.Add(context.Background(), 1, attributes)
	}
}

// AnalysisRequestTelemetry contains non-sensitive request metadata.
type AnalysisRequestTelemetry struct {
	Collection      string
	ProviderName    string
	ProviderProfile string
	Workload        string
	RequestModel    string
	ServerAddress   string
	ServerPort      int
	PromptVersion   string
	SchemaVersion   string
	JobID           int64
	Repository      string
	PullRequest     int
	Chunk           int
	Chunks          int
}

// AnalysisOutcomeTelemetry contains non-sensitive provider response metadata.
type AnalysisOutcomeTelemetry struct {
	Status                string
	FailureKind           string
	ErrorType             string
	ResponseModel         string
	ResponseID            string
	FinishReasons         []string
	InputTokens           *int64
	OutputTokens          *int64
	CachedInputTokens     *int64
	ReasoningOutputTokens *int64
	InputComponents       []ContentMeasurement
	OutputComponents      []ContentMeasurement
}

// StartAnalysis records one model analysis without prompt or response content.
func StartAnalysis(
	ctx context.Context, request AnalysisRequestTelemetry,
) (context.Context, func(AnalysisOutcomeTelemetry)) {
	if !instrumentsReady.Load() {
		return ctx, func(AnalysisOutcomeTelemetry) {}
	}
	counterAttributes := []attribute.KeyValue{
		attribute.String("maintainer_cockpit.collection", request.Collection),
	}
	if request.ProviderName != "" {
		counterAttributes = append(counterAttributes,
			attribute.String("gen_ai.provider.name", request.ProviderName))
	}
	if request.RequestModel != "" {
		counterAttributes = append(counterAttributes,
			attribute.String("gen_ai.request.model", request.RequestModel))
	}
	metricAttributes := append([]attribute.KeyValue{}, counterAttributes...)
	metricAttributes = appendGenAIAttributionAttributes(metricAttributes, request)
	metricAttributes = append(metricAttributes, attribute.String("gen_ai.operation.name", "chat"))
	if request.ServerAddress != "" {
		metricAttributes = append(metricAttributes,
			attribute.String("server.address", request.ServerAddress))
		if request.ServerPort > 0 {
			metricAttributes = append(metricAttributes, attribute.Int("server.port", request.ServerPort))
		}
	}
	spanAttributes := append([]attribute.KeyValue{}, metricAttributes...)
	spanAttributes = append(spanAttributes,
		attribute.String("gen_ai.output.type", "json"),
		attribute.String("gen_ai.prompt.name", "maintainer_cockpit.analysis"),
	)
	spanAttributes = appendGenAISpanAttributes(spanAttributes, request)
	analysisAttempts.Add(ctx, 1, metric.WithAttributes(counterAttributes...))
	spanName := "chat"
	if request.RequestModel != "" {
		spanName += " " + request.RequestModel
	}
	ctx, span := otel.Tracer(InstrumentationName).Start(
		ctx, spanName,
		trace.WithSpanKind(trace.SpanKindClient),
		trace.WithAttributes(spanAttributes...),
	)
	started := time.Now()
	return ctx, func(outcome AnalysisOutcomeTelemetry) {
		finalMetricAttributes := append([]attribute.KeyValue{}, metricAttributes...)
		if outcome.ResponseModel != "" {
			span.SetAttributes(attribute.String("gen_ai.response.model", outcome.ResponseModel))
			finalMetricAttributes = append(finalMetricAttributes,
				attribute.String("gen_ai.response.model", outcome.ResponseModel))
		}
		if outcome.ResponseID != "" {
			span.SetAttributes(attribute.String("gen_ai.response.id", outcome.ResponseID))
		}
		if len(outcome.FinishReasons) > 0 {
			span.SetAttributes(attribute.StringSlice(
				"gen_ai.response.finish_reasons", outcome.FinishReasons,
			))
		}
		if outcome.ErrorType != "" {
			span.SetAttributes(attribute.String("error.type", outcome.ErrorType))
			finalMetricAttributes = append(finalMetricAttributes,
				attribute.String("error.type", outcome.ErrorType))
		}
		genAIOperationDuration.Record(
			ctx, time.Since(started).Seconds(),
			metric.WithAttributes(finalMetricAttributes...),
		)
		tokenAttributes := finalMetricAttributes
		if outcome.InputTokens != nil {
			genAITokenUsage.Record(ctx, *outcome.InputTokens, metric.WithAttributes(
				append(tokenAttributes, attribute.String("gen_ai.token.type", "input"))...,
			))
		}
		if outcome.OutputTokens != nil {
			genAITokenUsage.Record(ctx, *outcome.OutputTokens, metric.WithAttributes(
				append(tokenAttributes, attribute.String("gen_ai.token.type", "output"))...,
			))
		}
		recordGenAIAttribution(ctx, span, finalMetricAttributes, outcome)
		switch {
		case outcome.Status == "complete":
			analysisSuccesses.Add(ctx, 1, metric.WithAttributes(counterAttributes...))
		case outcome.FailureKind == "provider":
			providerFailures.Add(ctx, 1, metric.WithAttributes(counterAttributes...))
			span.SetStatus(codes.Error, "provider failed")
		case outcome.FailureKind == "schema":
			schemaFailures.Add(ctx, 1, metric.WithAttributes(counterAttributes...))
			span.SetStatus(codes.Error, "schema validation failed")
		default:
			unknownAnalyses.Add(ctx, 1, metric.WithAttributes(counterAttributes...))
			span.SetStatus(codes.Error, "analysis unavailable")
		}
		span.End()
	}
}
